version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
  frontend:
    image: rperry2174/hotrod-golang:latest
    ports:
      - "8080:8080"
    command: ["frontend"]
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - PYROSCOPE_APPLICATION_NAME=hotrod.golang.frontend
      - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040
    depends_on:
      - jaeger
  customer:
    image: rperry2174/hotrod-golang:latest
    ports:
      - "8081:8081"
    command: ["customer"]
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - PYROSCOPE_APPLICATION_NAME=hotrod.golang.customer
      - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040
    depends_on:
      - jaeger
  driver:
    image: rperry2174/hotrod-golang:latest
    ports:
      - "8082:8082"
    command: ["driver"]
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - PYROSCOPE_APPLICATION_NAME=hotrod.golang.driver
      - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040
    depends_on:
      - jaeger
  route:
    image: rperry2174/hotrod-golang:latest
    ports:
      - "8083:8083"
    command: ["route"]
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - PYROSCOPE_APPLICATION_NAME=hotrod.golang.route
      - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040
    depends_on:
      - jaeger
  pyroscope:
    image: "pyroscope/pyroscope:latest"
    ports:
      - "4040:4040"
    command:
      - "server"